import { Section } from '@/components/section'
import { AmbientStudy } from '@/components/settle/ambient-study'
import { GoogleReference } from '@/components/settle/google-reference'
import { SnapshotStudy } from '@/components/settle/snapshot-study'

export function SectionField() {
  return (
    <Section id="field" title="A field, then an answer">
      <h2 className="text-4xl md:text-6xl font-bold tracking-tighter leading-[1.02] mb-6 max-w-4xl">a field, then an answer</h2>
      <p className="standfirst max-w-3xl">
        long, rounded bars give the waiting area a fuller shape. a few larger cells make room for one another, breathing on their own rhythms. the field can grow without chasing every word in a changing draft. sentences carry the visible material into their real word groups. the faster each-word option settles the ink in place, without sending pills across the page. new text settles once; earlier readable text stays still.
      </p>
      <div className="mt-12 md:mt-16"><AmbientStudy /></div>
      <p className="readout mt-6 leading-relaxed max-w-4xl" style={{ color: 'var(--muted)' }}>
        the gallery defaults to the observed capture clock. half-speed inspection gives the motion more time without claiming faster generation. reader benefits and physical iphone behavior remain untested.{' '}
        <a className="underline underline-offset-4" href="https://github.com/globalanomalyindex/after-tokens/blob/main/docs/growing-skeleton-v8-handoff-2026-09-12.md">motion rationale and proposed reader study</a>
      </p>
      <GoogleReference assetBase={process.env.GITHUB_PAGES === 'true' ? '/after-tokens' : ''} />
      <SnapshotStudy />
      <div className="mt-12 md:mt-16 grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)] rule pt-8">
        <h3 className="text-2xl md:text-3xl font-bold tracking-tight leading-tight">borrow the familiarity.<br />reconsider the promise.</h3>
        <div className="text-base leading-relaxed max-w-[64ch]" style={{ color: 'var(--ink-2)' }}>
          <p>A website skeleton usually previews a structure that already exists. Generated text may not yet have a known length, list count or line break. I start with five authored rows, then reserve more room from a coarse measure of content already received. Individual bar widths stay decorative: they do not trace a provisional sentence or claim to know the final layout. A source that supplies only its completed answer keeps the initial allocation until that answer arrives.</p>
          <p className="mt-4">The reference is a familiar solid-row loader. Its original code uses a traveling shimmer; this experiment pairs solid cell bodies with slow local breaths and an occasional coordinated glimmer. Pulsing and static skeletons already exist, so neither is claimed as an invention. The longer bars keep that familiar silhouette; smaller groups add variety without assigning a pill to every word. Readers could still mistake their movement for words becoming certain, so that interpretation needs testing. <a className="underline underline-offset-4" href="https://www.cssscript.com/skeleton-loader-placeholder/">reference</a>; <a className="underline underline-offset-4" href="https://github.com/zalog/placeholder-loading">original implementation</a>; <a className="underline underline-offset-4" href="https://mui.com/material-ui/react-skeleton/">MUI skeleton variants</a>.</p>
        </div>
      </div>
      <div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)]">
        <h3 className="text-2xl md:text-3xl font-bold tracking-tight leading-tight">a new shape.<br />room made around it.</h3>
        <div className="text-base leading-relaxed max-w-[64ch]" style={{ color: 'var(--ink-2)' }}>
          <p>Reshape is selected first at every width. One capsule opens into a mix of long bars and small groups of larger cells. Some full rows hold their shape; other rows make a slow, complete change, then hold until their next independently timed cue. Each change takes about 1.3–1.8 seconds at the default tempo. Targets stay unchanged between cues, so the material does not repeatedly chase a moving endpoint. The left margin and typographic spacing remain anchored. Still holds the material; Breathe retains the soft pulse without local reshaping. All three can reserve more room under the same sizing rule. A faint shared glimmer supplies an occasional coordinated accent.</p>
          <p className="mt-4">This combines an opening capsule, independently reshaping rows and a shared glimmer. Comparing it with Breathe tests the whole treatment, not one psychological mechanism. The rhythm belongs to the interface; a dividing cell is a visual metaphor, not a token becoming certain. Common-fate research motivates coordination; a small controlled skeleton study found no significant perceived-speed or navigation advantage over spinners. Neither proves this treatment helps a reader. <a className="underline underline-offset-4" href="https://arxiv.org/html/1908.00661">Chalbi et al., 2020</a>; <a className="underline underline-offset-4" href="https://doi.org/10.1145/3232078.3232086">Mejtoft et al., 2018</a>.</p>
          <p className="mt-4">Apple&rsquo;s Liquid Glass and spring demonstrations inform the soft continuity, not the material itself. These bars remain opaque content placeholders. After the capsule opens, its rows keep their left edge and text-like alignment. Larger cells redistribute space within their row, while the full bars provide stable reference lines. Growing the container may move content below it; this is not a claim of zero layout shift. Exact amounts are authored choices to test. <a className="underline underline-offset-4" href="https://developer.apple.com/videos/play/wwdc2025/219/">Meet Liquid Glass</a>; <a className="underline underline-offset-4" href="https://developer.apple.com/videos/play/wwdc2023/10158/">Animate with springs</a>.</p>
          <p className="mt-4">All three conditions use the same source events, selected release policy and handover rules. Each sentence is the default in every preview; whole-answer release remains available for comparison. Once a batch is eligible, the browser measures its actual word groups and the bubbles visible at that moment. Over 280 ms, those bubbles travel and reshape toward the groups while the text fades in and settles by at most 1.5 px from its resting position. Full opacity is authored at 74 percent of the interval. If more room is needed, a separate 180 ms fit comes first. Browser scheduling can extend these timings. Earlier text does not animate again. Continuing batches borrow at most six nearby cells, as does a final batch when earlier text is already readable. The cells are captured before the remaining field moves below the new passage. While the source continues, that field refills over 160 ms alongside the 280 ms handover, avoiding a second refill fade after the words settle. Transfers that begin after source finality do not refill; a refill already underway can finish within the final fade. A first batch that is already the complete answer can use the whole visible field. Surplus bars and an unfinished opening capsule fade at finality. The frame keeps its reserved height through the 280 ms handover, then contracts over 180 ms. If every character was already readable, only the field fades before that contraction. Text can be ready before the container finishes moving. Earlier words do not receive another arrival. These are explicit presentation costs, not psychological constants. <a className="underline underline-offset-4" href="https://carbondesignsystem.com/elements/motion/overview/">Carbon motion guidance</a>.</p>
        </div>
      </div>
      <div className="mt-10 grid gap-10 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.5fr)]">
        <h3 className="text-2xl md:text-3xl font-bold tracking-tight leading-tight">format can arrive early.<br />a whole layout may not.</h3>
        <div className="text-base leading-relaxed max-w-[64ch]" style={{ color: 'var(--ink-2)' }}>
          <p>In the original recordings, 45 of 138 final newline characters commit before both neighboring words finish. In the new list capture, the pieces of “1.” commit at 649 ms; “Create” finishes at 3,270 ms. Those are real local events, classified retrospectively for this audit. They do not reveal the final list count, wrapping or independently finished items.</p>
          <p className="mt-4">An app-owned form or an enforced schema can guarantee containers earlier. A prompt asking for three items cannot guarantee compliance. This version uses a narrower signal: the approximate amount of currently received content can reserve height. Committed fragments and genuinely received revisable snapshots have different source contracts; neither supplies a trustworthy final line layout. The individual rows keep their own clock and seed. Exact word geometry is measured only when a passage is eligible to appear. A real integration still needs a trustworthy completion signal; ambient motion cannot supply one.</p>
          <p className="mt-4">The tradeoff is explicit. The estimate starts at five rows, can grow to fourteen and keeps its largest allocation while waiting at the same width. Active source-only updates are sampled every 600 ms, then size changes ease over 380 ms. Earlier reading retains at least four ambient rows below the text. This can reserve too much room or still require a final 180 ms fit before the 280 ms handover. Whole-answer release also gives up earlier reading. Height continuity and reader preference remain separate questions. <a className="underline underline-offset-4" href="https://fluent2.microsoft.design/components/web/react/core/skeleton/usage">Fluent skeleton guidance</a>; <a className="underline underline-offset-4" href="https://web.dev/articles/optimize-cls">layout-shift guidance</a>.</p>
        </div>
      </div>
    </Section>
  )
}
