import { expect, test } from '@playwright/test'

test('the authored hero offers a stable transcript, pause and an immediate welcome', async ({ page }) => {
  await page.goto('/')
  const hero = page.locator('[data-hero-intro]')
  await hero.scrollIntoViewIfNeeded()
  await expect(page.locator('h1')).toHaveText('after tokens')
  await expect(hero.locator('[data-hero-transcript]')).toHaveText('Question: What should diffusion text rendering look like? Answer: It should look like this. Welcome to after tokens.')
  await expect.poll(() => hero.locator('[data-hero-typed]').textContent()).not.toBe('')
  await hero.getByRole('button', { name: 'pause intro', exact: true }).click()
  await expect(hero).toHaveAttribute('data-paused', 'true')
  await page.waitForTimeout(60)
  const elapsed = await hero.getAttribute('data-elapsed-ms')
  await page.waitForTimeout(180)
  expect(await hero.getAttribute('data-elapsed-ms')).toBe(elapsed)
  await hero.getByRole('button', { name: 'show welcome', exact: true }).click()
  await expect(hero).toHaveAttribute('data-static', 'true')
  const answer = hero.locator('.settle')
  await expect(answer).toHaveAttribute('data-material', 'growing-cell-skeleton-v8')
  expect(await page.locator('.settle').evaluateAll((surfaces) => surfaces.map((surface) => surface.getAttribute('data-policy')).filter((policy) => policy !== 'sentence'))).toEqual([])
  await expect(answer).toHaveAttribute('data-visual-ready', 'true')
  expect(await answer.locator('.settle-page').textContent()).toBe('It should look like this.\nWelcome to after tokens.')
  expect(await hero.locator('[data-demo]').first().evaluate((root) => root.getAnimations({ subtree: true }).filter((animation) => animation.playState === 'running').length)).toBe(0)
})
