import type { BrandId, BrandTokens } from './types'

export const brands: Record<BrandId, BrandTokens> = {
  'after-tokens': {
    id: 'after-tokens',
    name: 'After tokens',
    surface: '#EBE7DA',
    surfaceTint: '#E2DCCB',
    ink: '#15140F',
    inkSecondary: '#2A2820',
    muted: '#636058',
    stage: '#0B0A08',
    stageText: '#EBE7DA',
    accent: '#F5F2EA',
    particleColor: '#EBE7DA',
    fontDisplay: 'var(--font-display)',
    fontBody: 'var(--font-display)',
    fontMono: 'var(--font-mono)',
    cornerRadius: 8,
  },
  halcyon: {
    id: 'halcyon',
    name: 'Halcyon',
    surface: '#1A1F28',
    surfaceTint: '#22293A',
    ink: '#D8D4C6',
    inkSecondary: '#A8A398',
    muted: '#7A7569',
    stage: '#0E1218',
    stageText: '#D8D4C6',
    accent: '#8AA093',
    particleColor: '#8AA093',
    fontDisplay: '"Tiempos Headline", Georgia, serif',
    fontBody: '"Tiempos Text", Georgia, serif',
    fontMono: 'var(--font-mono)',
    cornerRadius: 8,
  },
  felt: {
    id: 'felt',
    name: 'Felt',
    surface: '#A8453A',
    surfaceTint: '#923A30',
    ink: '#F4ECDC',
    inkSecondary: '#E0D8C8',
    muted: '#D4C8B2',
    stage: '#0B0A08',
    stageText: '#F4ECDC',
    accent: '#F4ECDC',
    particleColor: '#F4ECDC',
    fontDisplay: 'var(--font-display)',
    fontBody: 'var(--font-display)',
    fontMono: 'var(--font-mono)',
    cornerRadius: 12,
  },
  pulse: {
    id: 'pulse',
    name: 'Pulse',
    surface: '#E9EEF2',
    surfaceTint: '#DDE4EA',
    ink: '#1F2A36',
    inkSecondary: '#3D4956',
    muted: '#6A7480',
    stage: '#0F141B',
    stageText: '#E9EEF2',
    accent: '#6FA9B4',
    particleColor: '#6FA9B4',
    fontDisplay: 'var(--font-display)',
    fontBody: 'var(--font-display)',
    fontMono: 'var(--font-mono)',
    cornerRadius: 10,
  },
  voltage: {
    id: 'voltage',
    name: 'Voltage',
    surface: '#0A0D12',
    surfaceTint: '#12161D',
    ink: '#EBE7DA',
    inkSecondary: '#B8B3A4',
    muted: '#7A7669',
    stage: '#000000',
    stageText: '#EBE7DA',
    accent: '#FF5E1F',
    particleColor: '#FF5E1F',
    fontDisplay: 'var(--font-display)',
    fontBody: 'var(--font-mono)',
    fontMono: 'var(--font-mono)',
    cornerRadius: 4,
  },
}

export function getBrand(id: BrandId): BrandTokens {
  return brands[id] ?? brands['after-tokens']
}
