import type { Metadata } from 'next'
import { displayFont, monoFont } from '@/lib/fonts'
import { CursorFX } from '@/components/chrome/cursor-fx'
import './globals.css'

// Icons are static files with an env-gated prefix rather than the app/icon.tsx
// convention: under `output: export` the convention route emits an href that
// ignores basePath, which 404s the favicon on the github pages mirror.
const iconBase = process.env.GITHUB_PAGES === 'true' ? '/after-tokens' : ''

export const metadata: Metadata = {
  metadataBase: new URL('https://after-tokens.vercel.app'),
  title: 'After Tokens: AI interaction design case study',
  description:
    'An independent product design and engineering case study exploring a reveal system for text generated by diffusion language models, with a working prototype.',
  authors: [
    {
      name: 'Christopher Robin Fiore',
      url: 'https://github.com/globalanomalyindex',
    },
  ],
  creator: 'Christopher Robin Fiore',
  alternates: {
    canonical: '/',
  },
  icons: {
    icon: [{ url: `${iconBase}/icon.png`, type: 'image/png', sizes: '32x32' }],
    shortcut: `${iconBase}/favicon.ico`,
  },
  openGraph: {
    title: 'After Tokens: AI interaction design case study',
    description:
      'A product design and engineering case study exploring how diffusion-generated answers could settle into view, with a working prototype and playground.',
    url: '/',
    siteName: 'After Tokens',
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'After Tokens: AI interaction design case study',
    description:
      'A product design and engineering case study exploring how diffusion-generated answers could settle into view, with a working prototype and playground.',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${displayFont.variable} ${monoFont.variable}`}>
      <body>
        {children}
        {/* Pointer-fine, reduced-motion-aware layer: drives the crosshair cursor
            and the definition chips' proximity marching-ants. No-ops itself out
            on touch devices and when the visitor prefers reduced motion. */}
        <CursorFX />
      </body>
    </html>
  )
}
